name: build docker image
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: login registry
        run: echo ${{secrets.DOCKER_HUB_PASSWORD}} | docker login -u wizawu --password-stdin

      - name: build image
        run: make build-image

      - name: tag image
        run: docker tag containous/traefik wizawu/traefik:2.2-$(git log -1 --oneline | head -c 7)

      - name: push image
        run: docker push wizawu/traefik:2.2-$(git log -1 --oneline | head -c 7)
