name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: traefik

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: make build-image

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          VERSION=latest
          docker tag containous/traefik $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
